#sample database.yml for a development db in a project using postgresql
#consider making new one or modifying it so it shows Fizal's preferrred action, i.e. dev in sqlite3 but prod in postgresql

development:
adapter: postgresql
database: development
username: <%= ENV['PG_USER'] %>
password: <%= ENV['PG_PASS'] %>
host: localhost

production:
adapter: postgresql
database: <%= ENV['DATABASE_URL'] %>